USE [master]
GO

/****** Object:  Database [PojectBetterTeamsDb]    Script Date: 9/11/2018 7:30:36 πμ ******/
CREATE DATABASE [PojectBetterTeamsDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PojectBetterTeamsDb', FILENAME = N'D:\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PojectBetterTeamsDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PojectBetterTeamsDb_log', FILENAME = N'D:\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PojectBetterTeamsDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [PojectBetterTeamsDb] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PojectBetterTeamsDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PojectBetterTeamsDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PojectBetterTeamsDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PojectBetterTeamsDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PojectBetterTeamsDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PojectBetterTeamsDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [PojectBetterTeamsDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PojectBetterTeamsDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PojectBetterTeamsDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PojectBetterTeamsDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PojectBetterTeamsDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PojectBetterTeamsDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PojectBetterTeamsDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PojectBetterTeamsDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PojectBetterTeamsDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PojectBetterTeamsDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PojectBetterTeamsDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PojectBetterTeamsDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PojectBetterTeamsDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PojectBetterTeamsDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PojectBetterTeamsDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PojectBetterTeamsDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PojectBetterTeamsDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PojectBetterTeamsDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PojectBetterTeamsDb] SET  MULTI_USER 
GO

ALTER DATABASE [PojectBetterTeamsDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PojectBetterTeamsDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PojectBetterTeamsDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PojectBetterTeamsDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PojectBetterTeamsDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PojectBetterTeamsDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PojectBetterTeamsDb] SET  READ_WRITE 
GO

